name: CI
on:
  push:
    branches:
      - main
      - develop
      - release/*
    tags:
      - v*

permissions:
  contents: read

jobs:
  check-code-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install module
        run: |
          pip install wheel
          pip install -e .[dev]

#      - name: Check code format with Black
#        run: |
#          black --check .

#      - name: Check imports order with isort
#        run: |
#          isort --check-only .

      - name: Check code style with Flake8
        if: ${{ always() }}
        run: |
          flake8 .

  build-and-push-package:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/golang
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

